name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Grant GITHUB_TOKEN the permissions to push to the gh-pages branch
permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Using 9.0 based on your file listing

    - name: Publish with dotnet
      run: dotnet publish StackTower.csproj -c Release -o release --nologo

    # Blazor WASM on GitHub Pages hack: Copy index.html to 404.html
    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # Add .nojekyll to prevent ignoring folders starting with _
    - name: Add .nojekyll
      run: touch release/wwwroot/.nojekyll

    # Deploy to gh-pages branch
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: release/wwwroot
